import type { Keyboard, Locator, Mouse, Page } from "@playwright/test";

/**
 * What a Playwright call does to the page, for demo mode's wrapper on the
 * runtime's Page. Which calls are a Run's Interactions is the runtime's to
 * say, not this table's.
 * - `none` runs as it is: it reads, waits, builds a locator or configures.
 * - `act` acts on the page, so demo mode pauses first.
 * - `point` acts through the pointer, so it is also hit-tested.
 * - `click` clicks its element, so demo mode also cues it.
 */
export type CallKind = "none" | "act" | "point" | "click";

type Methods<T> = {
  [K in keyof T]-?: T[K] extends (...args: never[]) => unknown ? K : never;
}[keyof T];

// Every method of Playwright's Locator, Page, Keyboard and Mouse, so a
// Playwright release that adds one fails typecheck until it is classified.

export const locatorCalls = {
  all: "none",
  allInnerTexts: "none",
  allTextContents: "none",
  and: "none",
  ariaSnapshot: "none",
  blur: "act",
  boundingBox: "none",
  check: "click",
  clear: "act",
  click: "click",
  contentFrame: "none",
  count: "none",
  dblclick: "click",
  describe: "none",
  description: "none",
  dispatchEvent: "act",
  dragTo: "point",
  drop: "act",
  elementHandle: "none",
  elementHandles: "none",
  evaluate: "none",
  evaluateAll: "none",
  evaluateHandle: "none",
  fill: "act",
  filter: "none",
  first: "none",
  focus: "act",
  frameLocator: "none",
  getAttribute: "none",
  getByAltText: "none",
  getByLabel: "none",
  getByPlaceholder: "none",
  getByRole: "none",
  getByTestId: "none",
  getByText: "none",
  getByTitle: "none",
  hideHighlight: "none",
  highlight: "none",
  hover: "point",
  innerHTML: "none",
  innerText: "none",
  inputValue: "none",
  isChecked: "none",
  isDisabled: "none",
  isEditable: "none",
  isEnabled: "none",
  isHidden: "none",
  isVisible: "none",
  last: "none",
  locator: "none",
  normalize: "none",
  nth: "none",
  or: "none",
  page: "none",
  press: "act",
  pressSequentially: "act",
  screenshot: "none",
  scrollIntoViewIfNeeded: "act",
  selectOption: "act",
  selectText: "act",
  setChecked: "click",
  setInputFiles: "act",
  tap: "click",
  textContent: "none",
  toString: "none",
  type: "act",
  uncheck: "click",
  waitFor: "none",
  waitForFunction: "none",
} as const satisfies Record<Methods<Locator>, CallKind>;

/** The Page's actions take their element's selector first. */
export const pageCalls = {
  $: "none",
  $$: "none",
  $eval: "none",
  $$eval: "none",
  addInitScript: "none",
  addListener: "none",
  addLocatorHandler: "none",
  addScriptTag: "none",
  addStyleTag: "none",
  ariaSnapshot: "none",
  bringToFront: "none",
  cancelPickLocator: "none",
  check: "click",
  clearConsoleMessages: "none",
  clearPageErrors: "none",
  click: "click",
  close: "none",
  consoleMessages: "none",
  content: "none",
  context: "none",
  dblclick: "click",
  dispatchEvent: "act",
  dragAndDrop: "point",
  emulateMedia: "none",
  evaluate: "none",
  evaluateHandle: "none",
  exposeBinding: "none",
  exposeFunction: "none",
  fill: "act",
  focus: "act",
  frame: "none",
  frameLocator: "none",
  frames: "none",
  getAttribute: "none",
  getByAltText: "none",
  getByLabel: "none",
  getByPlaceholder: "none",
  getByRole: "none",
  getByTestId: "none",
  getByText: "none",
  getByTitle: "none",
  goBack: "act",
  goForward: "act",
  goto: "act",
  hideHighlight: "none",
  hover: "point",
  innerHTML: "none",
  innerText: "none",
  inputValue: "none",
  isChecked: "none",
  isClosed: "none",
  isDisabled: "none",
  isEditable: "none",
  isEnabled: "none",
  isHidden: "none",
  isVisible: "none",
  locator: "none",
  mainFrame: "none",
  off: "none",
  on: "none",
  once: "none",
  opener: "none",
  pageErrors: "none",
  pause: "none",
  pdf: "none",
  pickLocator: "none",
  prependListener: "none",
  press: "act",
  reload: "act",
  removeAllListeners: "none",
  removeListener: "none",
  removeLocatorHandler: "none",
  requestGC: "none",
  requests: "none",
  route: "none",
  routeFromHAR: "none",
  routeWebSocket: "none",
  screenshot: "none",
  selectOption: "act",
  setChecked: "click",
  setContent: "none",
  setDefaultNavigationTimeout: "none",
  setDefaultTimeout: "none",
  setExtraHTTPHeaders: "none",
  setInputFiles: "act",
  setViewportSize: "none",
  tap: "click",
  textContent: "none",
  title: "none",
  type: "act",
  uncheck: "click",
  unroute: "none",
  unrouteAll: "none",
  url: "none",
  video: "none",
  viewportSize: "none",
  waitForEvent: "none",
  waitForFunction: "none",
  waitForLoadState: "none",
  waitForNavigation: "none",
  waitForRequest: "none",
  waitForResponse: "none",
  waitForSelector: "none",
  waitForTimeout: "none",
  waitForURL: "none",
  workers: "none",
} as const satisfies Record<Methods<Page>, CallKind>;

/** The Page's navigations: they act on no element. */
export const navigations = new Set<string>([
  "goBack",
  "goForward",
  "goto",
  "reload",
]);

// No element, so nothing to hit-test or cue: each acts.
export const keyboardCalls = {
  down: "act",
  insertText: "act",
  press: "act",
  type: "act",
  up: "act",
} as const satisfies Record<Methods<Keyboard>, CallKind>;

export const mouseCalls = {
  click: "act",
  dblclick: "act",
  down: "act",
  move: "act",
  up: "act",
  wheel: "act",
} as const satisfies Record<Methods<Mouse>, CallKind>;
