// @vitest-environment node
import {
  SchematicTestRunner,
  type UnitTestTree,
} from "@angular-devkit/schematics/testing";
import { describe, expect, it } from "vitest";

// The built collection, as the Angular CLI loads it from the package.
const runner = new SchematicTestRunner(
  "@ayme-dev/angular",
  decodeURIComponent(
    new URL("../../schematics/collection.json", import.meta.url).pathname
  )
);
const { version } = (await import("../../package.json")).default;

type AngularJson = {
  projects: Record<
    string,
    {
      architect: Record<
        string,
        { builder: string; options?: Record<string, unknown> }
      >;
    }
  >;
};

/** A workspace generated by Angular's own schematics, with one application. */
async function workspace(application: { ssr: boolean; standalone?: boolean }) {
  const tree = await runner.runExternalSchematic(
    "@schematics/angular",
    "workspace",
    {
      name: "workspace",
      newProjectRoot: "projects",
      version: "22.2.1",
    }
  );
  return runner.runExternalSchematic(
    "@schematics/angular",
    "application",
    { name: "app", ...application },
    tree
  );
}

async function ngAdd(tree: UnitTestTree) {
  const messages: { level: string; message: string }[] = [];
  const subscription = runner.logger.subscribe(({ level, message }) =>
    messages.push({ level, message })
  );
  try {
    const result = await runner.runSchematic("ng-add", {}, tree);
    return { tree: result, messages };
  } finally {
    subscription.unsubscribe();
  }
}

const architect = (tree: UnitTestTree) =>
  tree.readJson("angular.json") as AngularJson;

describe.each([true, false])("a standalone app with ssr=%s", (ssr) => {
  it("switches the builders to custom-esbuild with Ayme's plugin, writes the plugin file and adds provideAyme()", async () => {
    const before = await workspace({ ssr });
    const buildBefore = architect(before).projects["app"]!.architect["build"]!;

    const { tree, messages } = await ngAdd(before);

    const { build, serve } = architect(tree).projects["app"]!.architect;
    expect(build!.builder).toBe("@angular-builders/custom-esbuild:application");
    expect(serve!.builder).toBe("@angular-builders/custom-esbuild:dev-server");
    // Every existing option stays, including the budgets and SSR settings.
    expect(build!.options).toEqual({
      ...buildBefore.options,
      plugins: [
        {
          path: "./ayme.plugin.mjs",
          options: { tsconfigPath: "projects/app/tsconfig.app.json" },
        },
      ],
    });
    expect((build as { configurations?: unknown }).configurations).toEqual(
      (buildBefore as { configurations?: unknown }).configurations
    );
    expect(tree.readText("ayme.plugin.mjs")).toBe(
      'export { default } from "@ayme-dev/unplugin-ayme/angular";\n'
    );
    const config = tree.readText("projects/app/src/app/app.config.ts");
    expect(config).toContain(
      "import { provideAyme } from '@ayme-dev/angular';"
    );
    expect(config).toMatch(/providers: \[[^\]]*provideAyme\(\)/s);
    if (ssr)
      expect(
        tree.readText("projects/app/src/app/app.config.server.ts")
      ).not.toContain("provideAyme");
    const manifest = tree.readJson("package.json") as {
      dependencies: Record<string, string>;
      devDependencies: Record<string, string>;
    };
    expect(manifest.dependencies["@ayme-dev/ayme"]).toBe(version);
    expect(manifest.devDependencies["@ayme-dev/unplugin-ayme"]).toBe(version);
    expect(manifest.devDependencies["@playwright/test"]).toBe("~1.62.1");
    // The custom-esbuild major follows the Angular major the workspace uses.
    const angularMajor =
      manifest.dependencies["@angular/core"]!.match(/\d+/)![0];
    expect(manifest.devDependencies["@angular-builders/custom-esbuild"]).toBe(
      `^${angularMajor}.0.0`
    );
    expect(messages.filter(({ level }) => level === "warn")).toEqual([]);
  });
});

it("maps Angular 19's builders and installs the matching custom-esbuild major", async () => {
  const before = await workspace({ ssr: true });
  const json = architect(before);
  const targets = json.projects["app"]!.architect;
  targets["build"]!.builder = "@angular-devkit/build-angular:application";
  targets["serve"]!.builder = "@angular-devkit/build-angular:dev-server";
  before.overwrite("angular.json", JSON.stringify(json, null, 2));
  const manifest = before.readJson("package.json") as {
    dependencies: Record<string, string>;
  };
  manifest.dependencies["@angular/core"] = "^19.0.0";
  before.overwrite("package.json", JSON.stringify(manifest, null, 2));

  const { tree, messages } = await ngAdd(before);

  const { build, serve } = architect(tree).projects["app"]!.architect;
  expect(build!.builder).toBe("@angular-builders/custom-esbuild:application");
  expect(serve!.builder).toBe("@angular-builders/custom-esbuild:dev-server");
  expect(
    (tree.readJson("package.json") as { devDependencies: object })
      .devDependencies
  ).toHaveProperty("@angular-builders/custom-esbuild", "^19.0.0");
  expect(tree.readText("projects/app/src/app/app.config.ts")).toContain(
    "provideAyme()"
  );
  expect(messages.filter(({ level }) => level === "warn")).toEqual([]);
});

it("keeps the @playwright/test version a project already has", async () => {
  const before = await workspace({ ssr: false });
  const manifest = before.readJson("package.json") as {
    devDependencies?: Record<string, string>;
  };
  manifest.devDependencies = {
    ...manifest.devDependencies,
    "@playwright/test": "^1.64.0",
  };
  before.overwrite("package.json", JSON.stringify(manifest, null, 2));

  const { tree } = await ngAdd(before);

  expect(
    (tree.readJson("package.json") as { devDependencies: object })
      .devDependencies
  ).toHaveProperty("@playwright/test", "^1.64.0");
});

it("leaves angular.json alone and prints the manual steps for another custom builder", async () => {
  const before = await workspace({ ssr: false });
  const json = architect(before);
  json.projects["app"]!.architect["build"]!.builder =
    "@angular-builders/custom-webpack:browser";
  before.overwrite("angular.json", JSON.stringify(json, null, 2));

  const { tree, messages } = await ngAdd(before);

  expect(tree.readText("angular.json")).toBe(before.readText("angular.json"));
  expect(tree.exists("ayme.plugin.mjs")).toBe(false);
  expect(
    (tree.readJson("package.json") as { devDependencies: object })
      .devDependencies
  ).not.toHaveProperty("@angular-builders/custom-esbuild");
  expect(tree.readText("projects/app/src/app/app.config.ts")).toBe(
    before.readText("projects/app/src/app/app.config.ts")
  );
  const warnings = messages
    .filter(({ level }) => level === "warn")
    .map(({ message }) => message)
    .join("\n");
  expect(warnings).toContain("@angular-builders/custom-webpack:browser");
  expect(warnings).toContain("ng add left angular.json alone");
  expect(warnings).toContain("build: @angular-builders/custom-webpack:browser");
  expect(warnings).toContain(
    'export { default } from "@ayme-dev/unplugin-ayme/angular";'
  );
  expect(warnings).toContain("ng add could not add provideAyme()");
});

it("leaves an NgModule app's modules alone and prints the provideAyme() step", async () => {
  const before = await workspace({ ssr: false, standalone: false });

  const { tree, messages } = await ngAdd(before);

  // Angular 20 names the module app-module.ts, Angular 19 app.module.ts.
  const sources: string[] = [];
  before.getDir("projects/app/src").visit((path) => void sources.push(path));
  const modules = sources.filter((path) => /app[.-]module\.ts$/.test(path));
  expect(modules).toHaveLength(1);
  for (const file of ["/projects/app/src/main.ts", ...modules])
    expect(tree.readText(file)).toBe(before.readText(file));
  expect(architect(tree).projects["app"]!.architect["build"]!.builder).toBe(
    "@angular-builders/custom-esbuild:application"
  );
  expect(messages.filter(({ level }) => level === "warn")).toEqual([
    {
      level: "warn",
      message: expect.stringContaining(
        "Add provideAyme() from @ayme-dev/angular to your application config's providers, or to your root NgModule's."
      ),
    },
  ]);
});

it("is safe to run again: no second plugin entry, no second provider, no warning", async () => {
  const { tree: once } = await ngAdd(await workspace({ ssr: true }));

  const { tree: twice, messages } = await ngAdd(once);

  for (const file of [
    "angular.json",
    "ayme.plugin.mjs",
    "projects/app/src/app/app.config.ts",
  ])
    expect(twice.readText(file)).toBe(once.readText(file));
  expect(messages.filter(({ level }) => level === "warn")).toEqual([]);
});

it("leaves an unrelated ayme.plugin.mjs and angular.json alone and prints the manual steps", async () => {
  const before = await workspace({ ssr: false });
  before.create(
    "ayme.plugin.mjs",
    "export default () => ({ name: 'other' });\n"
  );

  const { tree, messages } = await ngAdd(before);

  for (const file of ["angular.json", "ayme.plugin.mjs"])
    expect(tree.readText(file)).toBe(before.readText(file));
  const warnings = messages
    .filter(({ level }) => level === "warn")
    .map(({ message }) => message)
    .join("\n");
  expect(warnings).toContain(
    "ayme.plugin.mjs already exists and does not re-export Ayme's plugin"
  );
  expect(messages.map(({ message }) => message).join("\n")).not.toContain(
    "Ayme is set up"
  );
});

it("adds its entry beside a plugin whose path only contains ayme.plugin.mjs", async () => {
  const before = await workspace({ ssr: false });
  const json = architect(before);
  const build = json.projects["app"]!.architect["build"]!;
  build.options = {
    ...build.options,
    plugins: [{ path: "./ayme.plugin.mjs.previous" }],
  };
  before.overwrite("angular.json", JSON.stringify(json, null, 2));

  const { tree } = await ngAdd(before);

  expect(
    architect(tree).projects["app"]!.architect["build"]!.options!["plugins"]
  ).toEqual([
    { path: "./ayme.plugin.mjs.previous" },
    {
      path: "./ayme.plugin.mjs",
      options: { tsconfigPath: "projects/app/tsconfig.app.json" },
    },
  ]);
});
